$(document).ready(function(){
	$("#button1").click(function(){
		$("#01").hide(1000);
	});

});	
$(document).ready(function(){
	$("#01").click(function(){
		$(this).hide();
	})
})
$(document).ready(function(){
	$("#02").click(function(){
		$("#01").show(1000);
	})
})
$(document).ready(function(){
	$("#03").click(function(){
		alert("Ustundesiniz!!");
	})
})
$(document).ready(function(){
	$("#button2").click(function(){
		$("p").toggle(1000);
	})
})
$(document).ready(function(){
  $("#button3").click(function(){
  		
  		$("#div1").fadeOut(1000);
  		$("#div2").fadeOut(1000);
  		$("#div3").fadeOut(1000);
  		$("#div4").fadeOut(1000);
  });
});
$(document).ready(function(){
	$("#button4").click(function(){
		$("#div1").fadeIn(3000);
		$("#div2").fadeIn(3000);
		$("#div3").fadeIn(3000);
		$("#div4").fadeIn(3000);
	})
})